[length]

[sum_values]

[mean]

[median]

[minimum]

[maximum]

[standard_deviation]

[variance]

[skewness]

[root_mean_square]

[kurtosis]

[absolute_energy]

[mean_absolute_change]

[linear_trend]

[variance_larger_than_standard_deviation]

[ratio_beyond_r_sigma]
parameters = [
    { r = 0.5 },
    { r = 1.0 },
    { r = 1.5 },
    { r = 2.0 },
    { r = 2.5 },
    { r = 3.0 },
    { r = 5.0 },
    { r = 6.0 },
    { r = 7.0 },
    { r = 10.0 },
]

[large_standard_deviation]
parameters = [
    { r = 0.05 },
    { r = 0.1 },
    { r = 0.15 },
    { r = 0.2 },
    { r = 0.25 },
    { r = 0.3 },
    { r = 0.35 },
    { r = 0.4 },
    { r = 0.45 },
    { r = 0.5 },
    { r = 0.55 },
    { r = 0.6 },
    { r = 0.65 },
    { r = 0.7 },
    { r = 0.75 },
    { r = 0.8 },
    { r = 0.85 },
    { r = 0.9 },
    { r = 0.95 },
]

[symmetry_looking]
parameters = [
    { r = 0.05 },
    { r = 0.1 },
    { r = 0.15 },
    { r = 0.2 },
    { r = 0.25 },
    { r = 0.3 },
    { r = 0.35 },
    { r = 0.4 },
    { r = 0.45 },
    { r = 0.5 },
    { r = 0.55 },
    { r = 0.6 },
    { r = 0.65 },
    { r = 0.7 },
    { r = 0.75 },
    { r = 0.8 },
    { r = 0.85 },
    { r = 0.9 },
    { r = 0.95 },
]

[has_duplicate_max]

[has_duplicate_min]

[cid_ce]
parameters = [{ normalize = true }, { normalize = false }]

[absolute_maximum]

[absolute_sum_of_changes]

[count_above_mean]

[count_below_mean]

[count_above]
parameters = [{ t = 0.0 }]

[count_below]
parameters = [{ t = 0.0 }]

[first_location_of_maximum]

[first_location_of_minimum]

[last_location_of_maximum]

[last_location_of_minimum]

[longest_strike_above_mean]

[longest_strike_below_mean]

[has_duplicate]

[variation_coefficient]

[mean_change]

[ratio_value_number_to_time_series_length]

[sum_of_reoccurring_values]

[sum_of_reoccurring_data_points]

[percentage_of_reoccurring_values_to_all_values]

[percentage_of_reoccurring_values_to_all_datapoints]

[agg_linear_trend]
parameters = [
    { chunk_size = 5, aggregator = "mean" },
    { chunk_size = 5, aggregator = "min" },
    { chunk_size = 5, aggregator = "max" },
    { chunk_size = 5, aggregator = "var" },
    { chunk_size = 10, aggregator = "mean" },
    { chunk_size = 10, aggregator = "min" },
    { chunk_size = 10, aggregator = "max" },
    { chunk_size = 10, aggregator = "var" },
    { chunk_size = 50, aggregator = "mean" },
    { chunk_size = 50, aggregator = "min" },
    { chunk_size = 50, aggregator = "max" },
    { chunk_size = 50, aggregator = "var" },
]


[mean_n_absolute_max]
parameters = [{ n = 7 }]

[autocorrelation]
parameters = [
    { lag = 0 },
    { lag = 1 },
    { lag = 2 },
    { lag = 3 },
    { lag = 4 },
    { lag = 5 },
    { lag = 6 },
    { lag = 7 },
    { lag = 8 },
    { lag = 9 },
]

[quantile]
parameters = [
    { q = 0.1 },
    { q = 0.2 },
    { q = 0.3 },
    { q = 0.4 },
    { q = 0.6 },
    { q = 0.7 },
    { q = 0.8 },
    { q = 0.9 },
]

[number_crossing_m]
parameters = [{ m = -1.0 }, { m = 0.0 }, { m = 1.0 }]

[range_count]
parameters = [
    { min = -1.0, max = 1.0 },
    { min = -1_000_000_000_000.0, max = 0.0 },
    { min = 0.0, max = 1_000_000_000_000.0 },
]

[index_mass_quantile]
parameters = [
    { q = 0.1 },
    { q = 0.2 },
    { q = 0.3 },
    { q = 0.4 },
    { q = 0.5 },
    { q = 0.6 },
    { q = 0.7 },
    { q = 0.8 },
    { q = 0.9 },
]

[c3]
parameters = [{ lag = 1 }, { lag = 2 }, { lag = 3 }]

[time_reversal_asymmetry_statistic]
parameters = [{ lag = 1 }, { lag = 2 }, { lag = 3 }]

[number_peaks]
parameters = [{ n = 1 }, { n = 3 }, { n = 5 }, { n = 10 }, { n = 50 }]
