[package]
name = "tsfx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "tsfx"
crate-type = ["lib", "cdylib"]

[dependencies]
pyo3 = "0"
chrono = "0"
csv = "1"
ndarray = "0"
ndarray-stats = "0"
polars = { version = "0", features = [
  "polars-io",
  "lazy",
  "csv",
  "diff",
  "dynamic_group_by",
  "strings",
  "ndarray",
  "streaming",
] }
pyo3-polars = { version = "0", features = ["lazy"] }
linfa = "0"
linfa-linear = "0"
noisy_float = "0"
itertools = "0"
ordered-float = "4"

[dev-dependencies]
criterion = { version = "0", features = ["html_reports"] }

[[bench]]
name = "bench_main"
harness = false
